// stencil-component/src/components/hello-component/hello-component.tsx
import { Component, Prop, h } from '@stencil/core';
import { format } from '../../utils/utils';

@Component({
  tag: 'hello-component',
  shadow: true,
})
export class MyComponent {
  /**
   * The first name
   */
  @Prop() first: string;

  /**
   * The middle name
   */
  @Prop() middle: string;

  /**
   * The last name
   */
  @Prop() last: string;

  private getText(): string {
    return format(this.first, this.middle, this.last);
  }

  render() {
    return <div>Hello, World, I'm {this.getText()}</div>;
  }
}

// svelte-component/src/Hello.svelte
<!-- your code here -->
<svelte:options tag="hello-component" />
<script >
import  './Hi.svelte'
 export let first;
 export let middle; 
 export let last;

 function format(first, middle, last) {
  return (first || '') + (middle ? ` ${middle}` : '') + (last ? ` ${last}` : '');
}

 function getText() {
   return format(first, middle, last)
 }


  </script>
  <style>
      
  </style>
<hi-component  first="Stencil" last="'Don't call me a framework' JS"></hi-component>
