// stencil-component/src/components/hi-component/hi-component.tsx
import { Component, Prop, h } from '@stencil/core';
import { format } from '../../utils/utils';

@Component({
  tag: 'hi-component',
  shadow: true,
})
export class MyComponent {
  /**
   * The first name
   */
  @Prop() first: string;

  /**
   * The middle name
   */
  @Prop() middle: string;

  /**
   * The last name
   */
  @Prop() last: string;

  private getText(): string {
    return format(this.first, this.middle, this.last);
  }

  render() {
    return <div>Hi, World! I'm {this.getText()}</div>;
  }
}

// svelte-component/src/Hi.svelte
<!-- your code here -->
<svelte:options tag="hi-component" />
<script >

 export let first;
 export let middle; 
 export let last;

 function format(first, middle, last) {
  return (first || '') + (middle ? ` ${middle}` : '') + (last ? ` ${last}` : '');
}

function getText() {
   console.log(first, middle, last);
   return first + middle + last;
 }


  </script>
  <style>
      
  </style>
  <div>Hi, World! I'm {first} {getText()}</div>
